export interface CorridorPage {
  slug: string;
  country: string;
  currency: string;
  flag: string;
  title: string;
  description: string;
  ogTitle: string;
  context: string;
  bestOptions: { icon: string; label: string; detail: string; color: "emerald" | "blue" | "amber" | "zinc" }[];
  savingsAmount: number;
  savingsLossMonthly: string;
  savingsLossYearly: string;
  faq: { q: string; a: string }[];
}

export const CORRIDOR_PAGES: CorridorPage[] = [
  {
    slug: "send-money-indonesia",
    country: "Indonesia",
    currency: "IDR",
    flag: "\u{1F1EE}\u{1F1E9}",
    title: "Send Money from Hong Kong to Indonesia (2026) \u2014 Cheapest Ways Compared | WeeCove",
    description: "Compare the cheapest ways to send money from Hong Kong to Indonesia. Wise vs Western Union vs Remitly. Independent comparison with real rates.",
    ogTitle: "Send Money HK to Indonesia (2026) | WeeCove",
    context: "About 150,000 Indonesian domestic workers live in Hong Kong, making HK to Indonesia one of the busiest remittance corridors in Asia. Bank transfer is the most common method, with Dana and GoPay as popular mobile wallet options in Indonesia.",
    bestOptions: [
      { icon: "\u{1F4B0}", label: "Cheapest: Wise", detail: "Mid-market rate + HK$75 fee. No hidden markup. Delivers to BCA, BNI, Mandiri.", color: "emerald" },
      { icon: "\u26A1", label: "Fastest: Western Union", detail: "Cash pickup in minutes at thousands of locations across Indonesia. Higher markup (~4.2%).", color: "blue" },
      { icon: "\u{1F4F1}", label: "Best App: Remitly", detail: "Good rates with fast delivery to Indonesian bank accounts. User-friendly app.", color: "amber" },
      { icon: "\u{1F3E6}", label: "Large Transfers: OFX", detail: "Zero fees, competitive rates. Best for amounts over HK$50,000.", color: "zinc" },
    ],
    savingsAmount: 10000,
    savingsLossMonthly: "HK$200-400",
    savingsLossYearly: "HK$2,400-4,800",
    faq: [
      { q: "What is the cheapest way to send money to Indonesia from Hong Kong?", a: "Wise typically offers the best rate for bank transfers using the mid-market rate plus a small fee. For cash pickup, Western Union has the widest network but charges more through rate markup." },
      { q: "How long does a transfer from HK to Indonesia take?", a: "Western Union cash pickup: minutes. Wise bank transfer: 1-2 business days. Bank wire (HSBC/BOC): 2-5 business days." },
      { q: "Can I send money to Dana or GoPay from Hong Kong?", a: "Most international transfer services deliver to Indonesian bank accounts (BCA, BNI, Mandiri). Direct Dana/GoPay delivery is limited. Recipients can transfer from their bank to Dana/GoPay locally." },
      { q: "How much does it cost to send HK$10,000 to Indonesia?", a: "With Wise: ~HK$75 fee at mid-market rate, recipient gets approximately Rp 21,000,000. With Western Union: zero visible fee but ~4.2% rate markup means ~Rp 800,000 less received." },
    ],
  },
  {
    slug: "send-money-india",
    country: "India",
    currency: "INR",
    flag: "\u{1F1EE}\u{1F1F3}",
    title: "Send Money from Hong Kong to India (2026) \u2014 Cheapest Ways Compared | WeeCove",
    description: "Compare the cheapest ways to send money from Hong Kong to India. Wise vs Remitly vs Western Union. UPI support. Independent comparison.",
    ogTitle: "Send Money HK to India (2026) | WeeCove",
    context: "About 38,000 Indian workers live in Hong Kong. India received over $125 billion in remittances in 2025, the largest recipient globally. UPI (Unified Payments Interface) has made instant bank transfers the preferred receiving method.",
    bestOptions: [
      { icon: "\u{1F4B0}", label: "Cheapest: Wise", detail: "Mid-market rate + HK$80 fee. No hidden markup. Delivers to any Indian bank account.", color: "emerald" },
      { icon: "\u26A1", label: "Fastest via UPI: Remitly", detail: "Instant delivery via UPI. Slightly higher markup (~1.2%) but arrives in minutes.", color: "blue" },
      { icon: "\u{1F4CD}", label: "Cash Pickup: Western Union", detail: "Cash at thousands of agent locations across India. Highest cost (~4.1% markup).", color: "amber" },
      { icon: "\u{1F3E6}", label: "Large Transfers: OFX", detail: "Zero fees, good rates. Best for amounts over HK$50,000.", color: "zinc" },
    ],
    savingsAmount: 10000,
    savingsLossMonthly: "HK$200-400",
    savingsLossYearly: "HK$2,400-4,800",
    faq: [
      { q: "What is the cheapest way to send money from HK to India?", a: "Wise offers the lowest total cost for most amounts, using the mid-market rate plus a transparent fee. Remitly is slightly more expensive but offers instant UPI delivery." },
      { q: "Can I send money to UPI from Hong Kong?", a: "Yes. Remitly and WorldRemit support UPI delivery to Indian bank accounts. Wise delivers via standard bank transfer (1-2 days)." },
      { q: "How long does a transfer from HK to India take?", a: "Remitly via UPI: minutes. Wise bank transfer: 1-2 business days. Western Union cash pickup: minutes. Bank wire: 2-5 business days." },
      { q: "Do I need KYC for sending money to India?", a: "Yes. All licensed services require ID verification (HKID or passport). India's RBI also requires the recipient's PAN card for larger amounts." },
    ],
  },
  {
    slug: "send-money-china",
    country: "China",
    currency: "CNY",
    flag: "\u{1F1E8}\u{1F1F3}",
    title: "Send Money from Hong Kong to China (2026) \u2014 Cheapest Ways via Alipay & WeChat | WeeCove",
    description: "Compare the cheapest ways to send HKD to CNY. Wise vs Panda Remit vs BOC. Alipay, WeChat Pay, and bank transfer compared. Independent.",
    ogTitle: "Send Money HK to China (2026) | WeeCove",
    context: "Hong Kong to mainland China is one of the world's largest remittance corridors. Cross-border payment has been simplified with Alipay and WeChat Pay integration. Bank of China offers same-day cross-border transfers between HK and mainland accounts.",
    bestOptions: [
      { icon: "\u{1F43C}", label: "Specialist: Panda Remit", detail: "Best rate for HK to China. Delivers to Alipay, WeChat Pay, or bank. Zero fee, only 0.3% markup.", color: "emerald" },
      { icon: "\u{1F4B0}", label: "Transparent: Wise", detail: "Mid-market rate + HK$122 fee. Delivers to Alipay, WeChat, or bank in seconds.", color: "blue" },
      { icon: "\u{1F3E6}", label: "Same-Day: BOC", detail: "Same-day cross-border transfer between BOC HK and BOC mainland accounts. Zero fee, 1.2% markup.", color: "amber" },
      { icon: "\u{1F4F1}", label: "App-Based: Revolut", detail: "Good weekday rates, 0.5% markup + HK$5 fee. Convenient app experience.", color: "zinc" },
    ],
    savingsAmount: 10000,
    savingsLossMonthly: "HK$150-350",
    savingsLossYearly: "HK$1,800-4,200",
    faq: [
      { q: "What is the cheapest way to send money from HK to China?", a: "Panda Remit typically offers the best rate with zero fee and only 0.3% markup. Wise is close behind with mid-market rate but a higher flat fee (HK$122). BOC is best if you have accounts at both branches." },
      { q: "Can I send to Alipay or WeChat Pay from Hong Kong?", a: "Yes. Wise and Panda Remit both support delivery to Alipay and WeChat Pay, as well as direct bank transfer." },
      { q: "Are there limits on sending money to China?", a: "China has an annual foreign exchange quota of CNY equivalent of USD 50,000 per person. Amounts above this may require additional documentation." },
      { q: "How fast is the transfer?", a: "Panda Remit to Alipay/WeChat: minutes. Wise to Alipay/WeChat: seconds. BOC cross-border: same day. Traditional bank wire: 1-3 business days." },
    ],
  },
  {
    slug: "send-money-japan",
    country: "Japan",
    currency: "JPY",
    flag: "\u{1F1EF}\u{1F1F5}",
    title: "Send Money from Hong Kong to Japan (2026) \u2014 Cheapest Ways Compared | WeeCove",
    description: "Compare the cheapest ways to send HKD to JPY. Wise vs Revolut vs OFX. Best rates for remittance and travel. Independent comparison.",
    ogTitle: "Send Money HK to Japan (2026) | WeeCove",
    context: "Japan is the most popular travel destination for Hong Kong residents, with millions of trips per year. Beyond travel, there is a growing business and education corridor. The weak yen since 2023 has made Japan travel especially popular.",
    bestOptions: [
      { icon: "\u{1F4B0}", label: "Cheapest: Wise", detail: "Mid-market rate + HK$65 fee. Best overall value for sending yen.", color: "emerald" },
      { icon: "\u{1F4F1}", label: "Convenient: Revolut", detail: "Near mid-market rate (0.4% markup) + HK$5 fee. Great app for frequent travelers.", color: "blue" },
      { icon: "\u{1F3E6}", label: "Large Amounts: OFX", detail: "Zero fees, 0.7% markup. Best for large transfers over HK$50,000.", color: "amber" },
      { icon: "\u{1F4CD}", label: "Urgent: Western Union", detail: "Cash pickup in Japan at convenience stores. Higher cost (~4% markup).", color: "zinc" },
    ],
    savingsAmount: 10000,
    savingsLossMonthly: "HK$150-350",
    savingsLossYearly: "HK$1,800-4,200",
    faq: [
      { q: "What is the cheapest way to send money from HK to Japan?", a: "Wise offers the best rate using mid-market exchange rate + HK$65 fee. Revolut is a close second with 0.4% markup. Both are significantly cheaper than banks or Western Union." },
      { q: "Should I exchange HKD to JPY before traveling to Japan?", a: "Using Wise or Revolut gives better rates than airport money changers. If you have a Revolut card, you can spend directly in Japan at near mid-market rates on weekdays." },
      { q: "How long does a transfer from HK to Japan take?", a: "Wise: 1-2 business days. Revolut: 1-2 business days. OFX: 1-3 business days. Bank wire: 2-5 business days." },
      { q: "How much yen will I get for HK$10,000?", a: "At mid-market rate: approximately \u00A5185,500. With Wise: ~\u00A5184,200 (after fee). With a bank: ~\u00A5177,000 (after markup + fee). That is \u00A57,200 difference." },
    ],
  },
  {
    slug: "send-money-south-korea",
    country: "South Korea",
    currency: "KRW",
    flag: "\u{1F1F0}\u{1F1F7}",
    title: "Send Money from Hong Kong to South Korea (2026) \u2014 Cheapest Ways Compared | WeeCove",
    description: "Compare the cheapest ways to send HKD to KRW. Wise vs Revolut vs Western Union. Best rates for remittance and travel. Independent comparison.",
    ogTitle: "Send Money HK to South Korea (2026) | WeeCove",
    context: "South Korea is a top travel and cultural destination for Hong Kong residents. K-pop, K-drama, and Korean food culture drive frequent visits. There is also a growing Korean business community in Hong Kong.",
    bestOptions: [
      { icon: "\u{1F4B0}", label: "Cheapest: Wise", detail: "Mid-market rate + HK$65 fee. Best value for bank transfers to Korean accounts.", color: "emerald" },
      { icon: "\u{1F4F1}", label: "Convenient: Revolut", detail: "0.4% markup + HK$5 fee. Good app for travelers to Korea.", color: "blue" },
      { icon: "\u{1F3E6}", label: "Large Amounts: OFX", detail: "Zero fees, 0.7% markup. Best for transfers over HK$50,000.", color: "amber" },
      { icon: "\u{1F4CD}", label: "Urgent: Western Union", detail: "Quick transfers with cash pickup options. Higher cost (~4.1% markup).", color: "zinc" },
    ],
    savingsAmount: 10000,
    savingsLossMonthly: "HK$150-350",
    savingsLossYearly: "HK$1,800-4,200",
    faq: [
      { q: "What is the cheapest way to send money from HK to South Korea?", a: "Wise typically offers the lowest total cost with mid-market rate + HK$65 fee. Revolut is close with 0.4% markup. Both are much cheaper than banks which charge 4-5% markup plus fees." },
      { q: "How long does a transfer to South Korea take?", a: "Wise: 1-2 business days. Revolut: 1-2 business days. Western Union cash pickup: minutes. Bank wire: 2-5 business days." },
      { q: "How much won will I get for HK$10,000?", a: "At mid-market rate: approximately \u20A91,845,000. With Wise: ~\u20A91,833,000 (after fee). With a bank: ~\u20A91,760,000 (after markup + fee)." },
    ],
  },
  {
    slug: "send-money-thailand",
    country: "Thailand",
    currency: "THB",
    flag: "\u{1F1F9}\u{1F1ED}",
    title: "Send Money from Hong Kong to Thailand (2026) \u2014 Cheapest Ways Compared | WeeCove",
    description: "Compare the cheapest ways to send HKD to THB. Wise vs Remitly vs Western Union. PromptPay support. Independent comparison.",
    ogTitle: "Send Money HK to Thailand (2026) | WeeCove",
    context: "Thailand is a popular destination for Hong Kong travelers and there is a Thai worker community in Hong Kong. PromptPay, Thailand's instant payment system, has made receiving money faster and easier.",
    bestOptions: [
      { icon: "\u{1F4B0}", label: "Cheapest: Wise", detail: "Mid-market rate + HK$65 fee. Best value for bank transfers to Thai accounts.", color: "emerald" },
      { icon: "\u26A1", label: "PromptPay: Remitly", detail: "Delivers via PromptPay for instant arrival. 1.4% markup but fast.", color: "blue" },
      { icon: "\u{1F4CD}", label: "Cash Pickup: Western Union", detail: "Cash pickup across Thailand. Higher cost (~4.1% markup) but no bank account needed.", color: "amber" },
      { icon: "\u{1F3E6}", label: "Large Amounts: OFX", detail: "Zero fees, 0.7% markup. Best for amounts over HK$50,000.", color: "zinc" },
    ],
    savingsAmount: 10000,
    savingsLossMonthly: "HK$150-350",
    savingsLossYearly: "HK$1,800-4,200",
    faq: [
      { q: "What is the cheapest way to send money from HK to Thailand?", a: "Wise offers the best rate with mid-market exchange + HK$65 fee. For instant PromptPay delivery, Remitly is slightly more expensive but arrives immediately." },
      { q: "Can I send to PromptPay from Hong Kong?", a: "Yes. Remitly supports PromptPay delivery to Thai bank accounts. Wise delivers via standard bank transfer (1-2 days)." },
      { q: "How long does a transfer from HK to Thailand take?", a: "Remitly via PromptPay: minutes. Western Union cash pickup: minutes. Wise: 1-2 business days. Bank wire: 2-5 business days." },
      { q: "How much baht will I get for HK$10,000?", a: "At mid-market rate: approximately \u0E3F44,200. With Wise: ~\u0E3F43,900 (after fee). With a bank: ~\u0E3F42,200 (after markup + fee)." },
    ],
  },
  {
    slug: "send-money-taiwan",
    country: "Taiwan",
    currency: "TWD",
    flag: "\u{1F1F9}\u{1F1FC}",
    title: "Send Money from Hong Kong to Taiwan (2026) \u2014 Cheapest Ways Compared | WeeCove",
    description: "Compare the cheapest ways to send HKD to TWD. Wise vs Revolut vs OFX. Best rates for remittance. Independent comparison.",
    ogTitle: "Send Money HK to Taiwan (2026) | WeeCove",
    context: "Hong Kong and Taiwan share close cultural ties. There is migration in both directions, with some Hong Kong residents relocating to Taiwan in recent years. Bank transfers are the primary method for sending money.",
    bestOptions: [
      { icon: "\u{1F4B0}", label: "Cheapest: Wise", detail: "Mid-market rate + HK$75 fee. Best overall value for Taiwanese bank accounts.", color: "emerald" },
      { icon: "\u{1F4F1}", label: "Convenient: Revolut", detail: "0.5% markup + HK$5 fee. Good for smaller regular transfers.", color: "blue" },
      { icon: "\u{1F3E6}", label: "Large Amounts: OFX", detail: "Zero fees, 0.7% markup. Best for large transfers.", color: "amber" },
      { icon: "\u{1F4CD}", label: "Urgent: Western Union", detail: "Cash pickup available. Higher cost (~4.1% markup).", color: "zinc" },
    ],
    savingsAmount: 10000,
    savingsLossMonthly: "HK$150-300",
    savingsLossYearly: "HK$1,800-3,600",
    faq: [
      { q: "What is the cheapest way to send money from HK to Taiwan?", a: "Wise offers the lowest total cost with mid-market rate + HK$75 fee. Revolut is a close alternative with 0.5% markup. Banks charge 4-5% markup plus fees." },
      { q: "How long does a transfer to Taiwan take?", a: "Wise: 1-2 business days. Revolut: 1-2 business days. Bank wire: 2-5 business days." },
      { q: "How much NT$ will I get for HK$10,000?", a: "At mid-market rate: approximately NT$41,800. With Wise: ~NT$41,500 (after fee). With a bank: ~NT$39,800 (after markup + fee)." },
    ],
  },
  {
    slug: "send-money-uk",
    country: "United Kingdom",
    currency: "GBP",
    flag: "\u{1F1EC}\u{1F1E7}",
    title: "Send Money from Hong Kong to UK (2026) \u2014 Cheapest Ways for BN(O) Migrants | WeeCove",
    description: "Compare the cheapest ways to send HKD to GBP. Wise vs Revolut vs OFX. Best rates for BN(O) migrants and families. Independent comparison.",
    ogTitle: "Send Money HK to UK (2026) | WeeCove",
    context: "Since the BN(O) visa scheme launched in 2021, over 150,000 Hong Kong residents have moved to the UK. This has created a major remittance corridor with families sending money to support relatives or emigrants transferring their savings from HK.",
    bestOptions: [
      { icon: "\u{1F4B0}", label: "Cheapest: Wise", detail: "Mid-market rate + HK$55 fee. Faster Payments delivery in the UK.", color: "emerald" },
      { icon: "\u{1F4F1}", label: "Convenient: Revolut", detail: "0.4% markup + HK$5 fee. Popular with BN(O) migrants who already use Revolut in the UK.", color: "blue" },
      { icon: "\u{1F3E6}", label: "Large Savings: OFX", detail: "Zero fees, 0.7% markup. Best for transferring large savings (HK$100,000+).", color: "amber" },
      { icon: "\u{1F3DB}\u{FE0F}", label: "Same Bank: HSBC", detail: "Free transfers between HSBC HK and HSBC UK via Global Transfer. Rate markup applies.", color: "zinc" },
    ],
    savingsAmount: 50000,
    savingsLossMonthly: "HK$500-1,500",
    savingsLossYearly: "HK$6,000-18,000",
    faq: [
      { q: "What is the cheapest way to send money from HK to UK?", a: "Wise offers the lowest total cost with mid-market rate + HK$55 fee. For large one-off transfers of savings, OFX has zero fees and competitive rates." },
      { q: "Can I use HSBC Global Transfer?", a: "Yes, if you have both HSBC HK and HSBC UK accounts. Global Transfer is free but uses HSBC's exchange rate which includes 4-5% markup. Wise is usually cheaper." },
      { q: "How long does a transfer from HK to UK take?", a: "Wise via Faster Payments: 1-2 business days. Revolut: 1-2 business days. HSBC Global Transfer: 1-2 business days. Bank wire: 3-5 business days." },
      { q: "I am a BN(O) migrant. Best way to transfer savings?", a: "For large amounts (HK$50,000+), compare OFX (zero fee, low markup) and Wise (mid-market rate, flat fee). A HK$500,000 transfer via bank could cost you over 2,000 GBP in hidden markup vs Wise." },
    ],
  },
  {
    slug: "send-money-australia",
    country: "Australia",
    currency: "AUD",
    flag: "\u{1F1E6}\u{1F1FA}",
    title: "Send Money from Hong Kong to Australia (2026) \u2014 Cheapest Ways Compared | WeeCove",
    description: "Compare the cheapest ways to send HKD to AUD. Wise vs OFX vs Revolut. Best rates for HK migrants. Independent comparison.",
    ogTitle: "Send Money HK to Australia (2026) | WeeCove",
    context: "Australia has one of the largest Hong Kong diaspora communities, with over 100,000 HK-born residents. Migration has increased since 2020. Common reasons for transfers include family support, property purchases, and transferring savings.",
    bestOptions: [
      { icon: "\u{1F4B0}", label: "Cheapest: Wise", detail: "Mid-market rate + HK$55 fee. Best overall value for Australian bank accounts.", color: "emerald" },
      { icon: "\u{1F3E6}", label: "Large Amounts: OFX", detail: "Zero fees, 0.5% markup. Australian-founded company, strong AUD corridor. Best for HK$50,000+.", color: "blue" },
      { icon: "\u{1F4F1}", label: "Convenient: Revolut", detail: "0.4% markup + HK$5 fee. Good app for regular transfers.", color: "amber" },
      { icon: "\u{1F4CD}", label: "Urgent: Western Union", detail: "Bank deposit or cash pickup. Higher cost (~4% markup) but fast.", color: "zinc" },
    ],
    savingsAmount: 50000,
    savingsLossMonthly: "HK$500-1,500",
    savingsLossYearly: "HK$6,000-18,000",
    faq: [
      { q: "What is the cheapest way to send money from HK to Australia?", a: "Wise offers the best rate for most amounts. For large transfers (HK$50,000+), OFX is competitive with zero fees. Both are much cheaper than banks." },
      { q: "How long does a transfer from HK to Australia take?", a: "Wise: 1-2 business days. OFX: 1-3 business days. Bank wire: 3-5 business days." },
      { q: "How much AUD will I get for HK$100,000?", a: "At mid-market rate: approximately A$20,000. With Wise: ~A$19,890 (after fee). With a bank: ~A$19,100 (after markup + fee). That is A$790 difference." },
    ],
  },
  {
    slug: "send-money-canada",
    country: "Canada",
    currency: "CAD",
    flag: "\u{1F1E8}\u{1F1E6}",
    title: "Send Money from Hong Kong to Canada (2026) \u2014 Cheapest Ways Compared | WeeCove",
    description: "Compare the cheapest ways to send HKD to CAD. Wise vs OFX vs Revolut. Best rates for HK migrants in Canada. Independent comparison.",
    ogTitle: "Send Money HK to Canada (2026) | WeeCove",
    context: "Canada has the largest Hong Kong diaspora outside Asia, with over 300,000 HK-born residents primarily in Vancouver and Toronto. Migration waves in the 1990s and again since 2020 have created a major remittance corridor.",
    bestOptions: [
      { icon: "\u{1F4B0}", label: "Cheapest: Wise", detail: "Mid-market rate + HK$55 fee. Delivers to any Canadian bank.", color: "emerald" },
      { icon: "\u{1F3E6}", label: "Large Amounts: OFX", detail: "Zero fees, 0.6% markup. Best for transferring large savings (HK$100,000+).", color: "blue" },
      { icon: "\u{1F4F1}", label: "Convenient: Revolut", detail: "0.4% markup + HK$5 fee. Popular with younger migrants.", color: "amber" },
      { icon: "\u{1F4CD}", label: "Urgent: Western Union", detail: "Cash pickup at thousands of locations. Higher cost (~3.9% markup).", color: "zinc" },
    ],
    savingsAmount: 50000,
    savingsLossMonthly: "HK$500-1,500",
    savingsLossYearly: "HK$6,000-18,000",
    faq: [
      { q: "What is the cheapest way to send money from HK to Canada?", a: "Wise offers the lowest total cost for most amounts with mid-market rate + flat fee. For large transfers, OFX has zero fees and competitive rates." },
      { q: "How long does a transfer from HK to Canada take?", a: "Wise: 1-2 business days. OFX: 1-3 business days. Western Union cash pickup: minutes. Bank wire: 3-5 business days." },
      { q: "How much CAD will I get for HK$100,000?", a: "At mid-market rate: approximately C$17,900. With Wise: ~C$17,800 (after fee). With a bank: ~C$17,000 (after markup + fee). That is C$800 difference." },
    ],
  },
  {
    slug: "send-money-usa",
    country: "United States",
    currency: "USD",
    flag: "\u{1F1FA}\u{1F1F8}",
    title: "Send Money from Hong Kong to USA (2026) \u2014 Cheapest Ways Compared | WeeCove",
    description: "Compare the cheapest ways to send HKD to USD. Wise vs HSBC vs OFX. HKD is pegged to USD. Independent comparison.",
    ogTitle: "Send Money HK to USA (2026) | WeeCove",
    context: "The Hong Kong dollar is pegged to the US dollar at approximately 7.75-7.85, making HKD-USD one of the most stable exchange rate pairs in the world. Because of the peg, exchange rate markup from providers is typically much smaller than other corridors. The main cost difference comes from fees and transfer methods.",
    bestOptions: [
      { icon: "\u{1F4B0}", label: "Cheapest: Wise", detail: "Mid-market rate + HK$40 fee. Transparent pricing. ACH delivery to US bank accounts.", color: "emerald" },
      { icon: "\u{1F3E6}", label: "Competitive: HSBC", detail: "HKD-USD peg means HSBC offers tight rates (~0.5% markup). Free via HSBC Global Transfer.", color: "blue" },
      { icon: "\u{1F4BC}", label: "Large Amounts: OFX", detail: "Zero fees, 0.5% markup. Best for large transfers or regular payments.", color: "amber" },
      { icon: "\u{1F4F1}", label: "App-Based: Revolut", detail: "0.4% markup + HK$5 fee. Quick and convenient.", color: "zinc" },
    ],
    savingsAmount: 50000,
    savingsLossMonthly: "HK$200-500",
    savingsLossYearly: "HK$2,400-6,000",
    faq: [
      { q: "Is the HKD-USD exchange rate fixed?", a: "The HKD is pegged to USD at 7.75-7.85 by the Hong Kong Monetary Authority. The rate is very stable, meaning exchange rate markup from providers is smaller than other corridors." },
      { q: "What is the cheapest way to send HKD to USD?", a: "Because of the peg, rate differences are small. Wise offers the most transparent pricing. HSBC Global Transfer is free if you have both accounts but applies a small markup." },
      { q: "ACH or wire transfer?", a: "ACH is free but takes 2-3 business days. Wire transfer costs $15-25 but arrives same day or next day. Wise uses ACH by default." },
      { q: "How much USD will I get for HK$100,000?", a: "At mid-market rate: approximately $12,850. With Wise: ~$12,800 (after fee). The peg means all providers are relatively close for this corridor." },
    ],
  },
];

export function getCorridorBySlug(slug: string): CorridorPage | undefined {
  return CORRIDOR_PAGES.find((c) => c.slug === slug);
}
